# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ofe1 = Oferecimento.create(creditos: 6, semestre_ideal: 4, turma: "34", ofe_data: Time.strptime("01/02/2019", "%d/%m/%Y"), disciplina_id: 1)
ofe2 = Oferecimento.create(creditos: 4, semestre_ideal: 1, turma: "34", ofe_data: Time.strptime("01/02/2019", "%d/%m/%Y"), disciplina_id: 2)
ofe3 = Oferecimento.create(creditos: 4, semestre_ideal: 2, turma: "42", ofe_data: Time.strptime("01/02/2017", "%d/%m/%Y"), disciplina_id: 3)
ofe4 = Oferecimento.create(creditos: 4, semestre_ideal: 6, turma: "41", ofe_data: Time.strptime("01/02/2017", "%d/%m/%Y"), disciplina_id: 4)
# ofe5 = Oferecimento.create(creditos: 4, semestre_ideal: 4, turma: "33", ofe_data: Time.strptime("01/02/2015", "%d/%m/%Y"), disciplina_id: 5)
# ofe6 = Oferecimento.create(creditos: 3, semestre_ideal: 4, turma: "33", ofe_data: Time.strptime("01/02/2018", "%d/%m/%Y"), disciplina_id: 6)
# ofe7 = Oferecimento.create(creditos: 4, semestre_ideal: 2, turma: "41", ofe_data: Time.strptime("01/02/2019", "%d/%m/%Y"), disciplina_id: 7)
# ofe8 = Oferecimento.create(creditos: 4, semestre_ideal: 6, turma: "42", ofe_data: Time.strptime("01/02/2018", "%d/%m/%Y"), disciplina_id: 8)
# ofe9 = Oferecimento.create(creditos: 4, semestre_ideal: 5, turma: "41", ofe_data: Time.strptime("01/02/2019", "%d/%m/%Y"), disciplina_id: 9)
# ofe10 = Oferecimento.create(creditos: 6, semestre_ideal: 7, turma: "34", ofe_data: Time.strptime("01/02/2015", "%d/%m/%Y"), disciplina_id: 10)

Cursa.create(aluno_id: 1, oferecimento: ofe1)
Cursa.create(aluno_id: 1, oferecimento: ofe2)
Cursa.create(aluno_id: 1, oferecimento: ofe4)
Cursa.create(aluno_id: 2, oferecimento: ofe1)
Cursa.create(aluno_id: 2, oferecimento: ofe3)
Cursa.create(aluno_id: 3, oferecimento: ofe3)
Cursa.create(aluno_id: 3, oferecimento: ofe2)
Cursa.create(aluno_id: 4, oferecimento: ofe2)
Cursa.create(aluno_id: 4, oferecimento: ofe1)
Cursa.create(aluno_id: 5, oferecimento: ofe4)
Cursa.create(aluno_id: 6, oferecimento: ofe4)

Planeja.create(aluno_id: 1, disciplina_id: 1, nota: 7.0)
Planeja.create(aluno_id: 1, disciplina_id: 2, nota: 3.0)
Planeja.create(aluno_id: 1, disciplina_id: 4, nota: 5.0)
Planeja.create(aluno_id: 2, disciplina_id: 1, nota: 9.0)
Planeja.create(aluno_id: 3, disciplina_id: 2, nota: 10.0)
Planeja.create(aluno_id: 3, disciplina_id: 5, nota: 5.0)
Planeja.create(aluno_id: 4, disciplina_id: 2, nota: 4.5)
Planeja.create(aluno_id: 5, disciplina_id: 2, nota: 5.5)
Planeja.create(aluno_id: 6, disciplina_id: 3, nota: 3.5)
Planeja.create(aluno_id: 7, disciplina_id: 3, nota: 5.0)
Planeja.create(aluno_id: 7, disciplina_id: 7, nota: 8.5)
